name: urbanstay
description: "UrbanStay - PG and Hostel Operations Operating System"
publish_to: 'none'
version: 1.0.74+75

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_contacts: ^2.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Tenant_nameBG.png
    - assets/images/phone_mockup_tenant.png
    - assets/images/skyline_bengaluru.png
    - assets/images/gpay.svg
    - assets/images/phonepe.svg
    - assets/images/paytm.svg
    - assets/images/upi.svg
    - assets/images/whatsapp.svg
    - assets/images/phone.svg
